### PR TITLE
Licensing

### PR DESCRIPTION
**Pull request by delaere**
This PR adds additional information needed for the GPLv3 license. 
It also adds missing information about the copyright.

This has been prepared in collaboration with the UCL LTTO (Matthieu Palate).

### CODE REVIEW

**Comment by swertz** [comment]
Thanks, good to get that right! It'd be good to have that backported to the v0.1 and v1.0 branch, I suppose.

I am surprised we have to include so much about ROOT, Lua and LHAPDF, given that we don't redistribute them (contrary to cuba)? Because there are more dependencies than that (python and boost to begin with)...

**Comment by delaere** [comment]
Well, for LUA we do.

That said, there is a bit of grey zone there. We have to include/follow the licensing terms for all the dependencies , but there is an exception for the build system + standard libraries. So you don't have to mention python (language/compiler/interpreter), or boost (considered as a standard library). For ROOT and LHAPDF, linking to them is enough.

**Comment by swertz** [comment]
Right, forgot about lua... Ok, thanks again!

**Comment by swertz** [comment]
Something else I forgot about: we also ship the catch header-only library:
https://github.com/MoMEMta/MoMEMta/blob/master/tests/include/catch.hpp
https://github.com/catchorg/Catch2/

It's the boost license so there's no real issue there...

**Pull request merged**
