### PR TITLE
Create an install target for cmake

### PR DESCRIPTION
**Pull request by blinkseb**
The public headers files are now in 'include/momemta', while the private
ones are in 'src/'. Users will only be able to include public files into
their code, since only these headers will be installed.

This is needed to allow MoMEMta to be used in other softwares, and also to pave the way to modular inclusion of ME into the code.

### CODE REVIEW

**Comment by swertz** [comment]
Thanks! Wouldn't it be better to have the private headers and the sources in separate directories?

**Comment by blinkseb** [comment]
Yes why not. I actually have found both method recommended so it's up to you :)

**Comment by swertz** [comment]
With the present number of files in src/ it's fine but if it increases too much in the future it might become messy, no?

**Comment by blinkseb** [comment]
I agree. What about:

```
include/momemta
momemta/src
momemta/include
```
?

Or we can even move private headers back into `include` while letting public ones into `include/momemta`?

**Comment by swertz** [comment]
So, following the discussion online, the conclusion was to have
```
include/momemta
core/src
core/include
```
Right?

**Comment by blinkseb** [comment]
Yes indeed! I'll update the PR asap

**Comment by blinkseb** [comment]
It's done! I've moved everything in `core/`. Much cleaner now thanks!

**Comment by swertz** [comment]
Thanks!

**Pull request merged**
