### PR TITLE
Find threads in CMake

### PR DESCRIPTION
**Pull request by swertz**
Fixes build on ingrid. @blinkseb, what was the reason for requiring pthreads actually?

### CODE REVIEW

**Comment by blinkseb** [comment]
That's weird, it should be automatically done by the `FindBoost` package. I guess the version of cmake on ingrid is too old?

Thanks for the fix :)

`pthread` is required for multiple reasons, but the main one is that Boost.Log depends on Boost.Thread which depend on `pthread` on unix. It's should be to ensure that the logger is thread-safe.

**Comment by swertz** [comment]
Ok! I used the cmake 3.4 module, it's not that old...?

**Comment by blinkseb** [comment]
I bumped travis version to 3.5.2 (the latest) and I test on my laptop with 3.5.1, so it's probably something they added in 3.5...

**Comment by swertz** [comment]
Ok! I think we should not rely too much on the latest features, even if it's very tempting... ;) Some users might not have the choice of the version they use (even if a local installation of the latest is always an option).

**Comment by blinkseb** [comment]
I totally agree. I already bumped min version to 3.2, because support for Boost in previous version is utterly broken and fixing it would be a real pain in the ass.

But unfortunately, they don't document from which release a particular features is available, so, unless browsing git history, you don't know if you are using something new or now (see this PR :smile: )

**Pull request merged**
