### PR TITLE
Handle both versions of python

### PR DESCRIPTION
**Pull request by swertz**
Attempt at fixing #167 (see the issue for a more complete description)

I still need to update the README - I'll do this if you think this is an acceptable solution.

It also needs to be tested under different environments (it works on my laptop with 'buntu). And it'd be good to have travis test cases with python3, too.

### CODE REVIEW

**Comment by delaere** [comment]
I have an issue here... I tried on my machine and the version of boost is more recent, so I had to patch the findBoost code. Still, there are many difference between the system version and my patched version. We should find a way to do the same without replacing the full findBoost.cmake.

Maybe related, when I finally compile with the python3 bindings, I end up with the following error when running the tests:
>Traceback (most recent call last):
>  File "/home/delaer/Tools/MoMEMta/tests/bindings/python/integration_tests.py", line 31, in test_pyroot
>    p3 = momemta.Particle("electron", LorentzVector(16.171895980835, -13.7919054031372, -3.42997527122497, 21.5293197631836))
>Boost.Python.ArgumentError: Python argument types in
>    Particle.__init__(Particle, str, LorentzVector<ROOT::Math::PxPyPzE4D<double> >)
did not match C++ signature:
>    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >, long)
>    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >)
>    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

**Comment by swertz** [comment]
And your PyROOT is built with the same python version?

**Comment by delaere** [comment]
I think so.
Initially I was missing the python3-root package and cmake failed. But strangely, /usr/lib64/root/libPyROOT.so is the same for python3-root and python2-root and refers to libpython2.7.so.1.0 ! So maybe a packaging issue in Fedora.

**Comment by delaere** [comment]
ok, the packaging issue is confirmed. I unsinstalled python2-root and reinstalled python3-root and it works. So python2-root  and python3-root cannot coexist on Fedora!

**Comment by swertz** [comment]
I think that's the case everywhere, it's not possible to have pyroot for both versions of python (unless you build it twice, but the libraries have the same name).

Great that it worked, but there's another issue on ingrid: cmake doesn't find python 3 at all...

**Comment by swertz** [comment]
Or, for some reason, when the order of `find_package(PythonInterp)` and `find_package(PythonLibs)` is inverted, it works.

There is still an issue in that boost::python is only available for python2 on ingrid, but that's not a problem with MoMEMta...

**Comment by delaere** [comment]
We should still find a better solution for findBoost... maintaining it could become a nightmare, especially for the _Boost_COMPONENT_DEPENDENCIES function.

**Comment by swertz** [comment]
You're right... Here's another attempt that seems to work on my laptop. The `Boost_PYTHON_VERSION_TAG` variable still has to be passed by the user, but I was able to use that tag to modify our own cmake config to use the default boost cmake module.

**Comment by delaere** [comment]
Works for me too. I have a warning about boost headers, but I suppose that we can ignore it.

**Comment by swertz** [comment]
I do too, but the build is fine... There's still a confusing issue with boost_python on ingrid (see https://cp3-git.irmp.ucl.ac.be/cp3-support/helpdesk/issues/1572), that has to be solved before I'm sure we can merge this.

**Comment by swertz** [comment]
Ok, it seems to work fine now! I've updated the README for the new build options.

I only have one peculiar issue: when building with `-DPROFILING=ON` (with `gperftools` installed!), I the python unit test fails:
```
Error in `/usr/bin/python3': free(): invalid pointer: 0x00000000029290e0
```
Googling a bit I couldn't find much, but it seems that when linking with `gperftools`, the standard `malloc()` calls get replaced by something else, and that could be the source of the issue. 

It doesn't look easy to fix, but it's perhaps not urgent given that users will rarely want to profile anyway?

**Comment by swertz** [comment]
I've found the issue with the profiling: two additional libraries are linked, `tcmalloc` for heap profiling & checking, and `profiler` for CPU profiling. The problem is, while the python module library is linked again `tcmalloc`, python itself is not, hence the mismatch...

The solution is then to do e.g. `LD_PRELOAD=(path to tcmalloc) ./run_tests.sh` to make sure `tcmalloc` is available for everyone. I'll update the PR.

**Comment by swertz** [comment]
Updated again, and I hope for the last time!

**Comment by vidalm** [comment]
Thanks a lot btw!!

**Pull request merged**
