### PR TITLE
Move math functions from Utils.h to Math.h

### PR DESCRIPTION
**Pull request by blinkseb**
Move things from `Utils.h` to `Unused.h` and `Math.h`

 - `Math.h` contains all the maths functions
 - `Unused.h` contains the `UNUSED` declaration
 - `Utils.h` keeps functions I have no clue where to put otherwise :)

I also used `clang-formatter` to reformat the source code of math functions.

### CODE REVIEW

**Comment by swertz** [comment]
Thanks! This will break compatibility with the Tutorials: we need a way to follow the versioning of MoMEMta there... Maybe also parallel branches: a "v0.1.x" which is guaranteed to work with the "v0.1.x" of MoMEMta, and a "master" which might not always be up-to-date with the "master" or MoMEMta? And same thing with the exporter...

**Comment by blinkseb** [comment]
Ah, you're right, forgot about that. Seems like a good strategy indeed

**Comment by swertz** [comment]
Did you try to build external stuff (like a generated ME) with theses changes? The Tutorials are obviously broken; the ME should not be affected by this but since we've had issues with the include chains before I'd like to be sure...

**Comment by blinkseb** [comment]
Nope, just did a full build of MoMEMta. But since I did not edit any matrix element files, risk of breakage are low. But indeed, it's better to check

**Comment by swertz** [comment]
Works fine! Thanks again!

**Comment by blinkseb** [comment]
Many thanks for testing!

**Pull request merged**
