### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by blinkseb**
This PR introduce python bindings for MoMEMta, allowing to compute MEM weights directly from python :) Not all MoMEMta is exposed to python, but enough is to actually:
 - Parse configuration file
 - Edit parameters
 - Compute weights

Included in this PR is an integration test in python, computing weights and checking it's correct.

Bindings are not built by default, you have to add the `-DPYTHON_BINDINGS=ON` flag when running cmake. Python and boost::python are both needed for the bindings. If they are not available, bindings are not built. Also, if one want support for pyroot, then ROOT has obviously to be built with pyroot. If it's not the case, bindings are built, but without pyroot support.

TODO:
 - ~~Install target is missing for the python bindings~~ done

### CODE REVIEW

**Comment by swertz** [comment]
That's really awesome! :)

Can you update the changelog?

**Comment by blinkseb** [comment]
Duh, of course :smile:

**Comment by blinkseb** [comment]
Changelog updated!

**Comment by swertz** [comment]
Muchas gracias!

**Pull request merged**
