### PR TITLE
Protect against NaN or inf integrands; reset ME at start of each integration

### PR DESCRIPTION
**Pull request by swertz**
- Protect against NaN of inf integrands: throw exception when integrand is non-finite. I'm actually not sure about this: maybe want not to crash the program but return a specific failure code for the integration? I think it'd be more easily missed...
- Reset ME at start of each integration: goes with update in the exporter

### CODE REVIEW

**Comment by swertz** [comment]
Fixes #155

**Comment by blinkseb** [comment]
Thanks a bunch! I think I prefer to throw an exception rather than returning a special code: a NaN is very bad, as it implies a bug somewhere, so this should not be un-noticed!

Let's see if travis is happy!

**Comment by swertz** [comment]
It should work now, I had forgotten to update the particle PIDs in all the config files using the ttbar ME (I inadvertedly changed from mu+/e- to mu+/mu- final state, and was too lazy to re-generate the ME).

**Comment by blinkseb** [comment]
Good to see our tests seem at least to be useful 👍

**Comment by swertz** [comment]
I always forget to run the tests without pushing :D It seems fine now!

**Comment by blinkseb** [comment]
Thanks a lot!

**Pull request merged**
